version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: rater-redis
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rater-gateway
    ports:
      - "8082:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - SERVICE_ADDR=https://jsonplaceholder.typicode.com/users
    depends_on:
      - redis
    restart: unless-stopped
